name: dart_chess_pieces
description: A Dart package for creating and managing chess games, including board setup, piece movement, and game state management.
version: 1.2.0
repository: https://github.com/jun-young1993/dart_chess_pieces
homepage: https://juny.blog

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  font_awesome_flutter: ^10.7.0
  flutter:
    sdk: flutter
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
