name: dart_chess_pieces
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/jun-young1993/dart_chess_pieces
homepage: "https://juny.blog"

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
